const ASSET_ROOT='https://raw.githubusercontent.com/ErChulo/dandys-world/main/assets';
const characters=[
{name:'Astro',slug:'astro'},{name:'Boxter',slug:'boxten'},{name:'Brightney',slug:'brightney'},{name:'Cosmo',slug:'cosmo'},{name:'Finn',slug:'finn'},{name:'Goob',slug:'goob'},{name:'Glisten',slug:'glisten'},{name:'Poppy',slug:'poppy'},{name:'Rodger',slug:'rodger'},{name:'Razzle & Dazzle',slug:'razzle-dazzle'},{name:'Dandy',slug:'dandy'},{name:'Scraps',slug:'scraps'},{name:'Shrimpo',slug:'shrimpo'},{name:'Teagan',slug:'teagan'},{name:'Tisha',slug:'tisha'},{name:'Toodles',slug:'toodles'},{name:'Flutter',slug:'flutter'},{name:'Pebble',slug:'pebble'},{name:'Shelly',slug:'shelly'},{name:'Vee',slug:'vee'},{name:'Sprout',slug:'sprout'}];
const paletteColors=['#ff4f87','#ff9f43','#ffd93d','#6bdb75','#48d8c8','#43b4ff','#6b6cff','#b06cff','#ed73c6','#8b5a3c','#222222','#ffffff'];
const pickerScreen=document.querySelector('#pickerScreen'),colorScreen=document.querySelector('#colorScreen'),carousel=document.querySelector('#carousel'),danceCharacter=document.querySelector('#danceCharacter'),selectedName=document.querySelector('#selectedName'),pageTitle=document.querySelector('#pageTitle'),pageNumber=document.querySelector('#pageNumber'),paintCanvas=document.querySelector('#paintCanvas'),lineCanvas=document.querySelector('#lineCanvas'),canvasShell=document.querySelector('#canvasShell'),paintCtx=paintCanvas.getContext('2d'),lineCtx=lineCanvas.getContext('2d');
const lineArtImage=new Image();lineArtImage.crossOrigin='anonymous';
let selectedIndex=0,currentColor=paletteColors[0],brushSize=28,erasing=false,drawing=false,lastPt=null,pageVariant=1,activeSaveId=null,resizeTimer=null,carouselPaused=false,carouselDirection=1,carouselRAF=null,carouselLastTs=0,carouselResumeTimer=null,carouselPosition=0;const carouselSpeed=24;
function spriteUrl(c){return `${ASSET_ROOT}/sprites/${c.slug}.png`}
function lineUrl(c){return `${ASSET_ROOT}/lineart/${c.slug}.png`}
function spriteStyle(el,c){el.style.backgroundImage=`url('${spriteUrl(c)}')`;el.style.backgroundSize='contain';el.style.backgroundPosition='center';el.style.backgroundRepeat='no-repeat'}
function maxCarouselScroll(){return Math.max(0,carousel.scrollWidth-carousel.clientWidth)}
function pauseCarousel(){carouselPaused=true}
function resumeCarousel(){if(pickerScreen.classList.contains('hidden'))return;carouselPaused=false;carouselLastTs=0}
function scheduleCarouselResume(delay=800){clearTimeout(carouselResumeTimer);carouselResumeTimer=setTimeout(resumeCarousel,delay)}
function continuousCarouselTick(ts){if(!carouselLastTs){carouselLastTs=ts;carouselPosition=carousel.scrollLeft}const dt=Math.min(40,ts-carouselLastTs)/1000;carouselLastTs=ts;if(!carouselPaused&&!pickerScreen.classList.contains('hidden')){const max=maxCarouselScroll();if(max>0){carouselPosition+=carouselSpeed*dt*carouselDirection;if(carouselPosition>=max){carouselPosition=max;carouselDirection=-1}else if(carouselPosition<=0){carouselPosition=0;carouselDirection=1}carousel.scrollLeft=carouselPosition}}else carouselPosition=carousel.scrollLeft;carouselRAF=requestAnimationFrame(continuousCarouselTick)}
function startCarouselMotion(){if(carouselRAF)cancelAnimationFrame(carouselRAF);carouselLastTs=0;carouselRAF=requestAnimationFrame(continuousCarouselTick)}
function setupCarouselMotion(){carousel.addEventListener('pointerdown',()=>{pauseCarousel();carouselPosition=carousel.scrollLeft},{passive:true});const release=()=>{carouselPosition=carousel.scrollLeft;scheduleCarouselResume(650)};carousel.addEventListener('pointerup',release,{passive:true});carousel.addEventListener('pointercancel',release,{passive:true});carousel.addEventListener('touchend',release,{passive:true});carousel.addEventListener('touchcancel',release,{passive:true});carousel.addEventListener('wheel',()=>{pauseCarousel();carouselPosition=carousel.scrollLeft;scheduleCarouselResume(1000)},{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseCarousel();else{carouselPosition=carousel.scrollLeft;resumeCarousel()}});requestAnimationFrame(()=>requestAnimationFrame(()=>{carouselPosition=carousel.scrollLeft;resumeCarousel();startCarouselMotion()}))}
function buildCarousel(){characters.forEach((c,i)=>{const btn=document.createElement('button');btn.className='carousel-card';btn.type='button';btn.setAttribute('aria-label',`Choose ${c.name}`);const thumb=document.createElement('div');thumb.className='thumb-sprite';spriteStyle(thumb,c);const label=document.createElement('span');label.textContent=c.name;btn.append(thumb,label);btn.addEventListener('click',()=>selectCharacter(i,true));carousel.appendChild(btn)});selectCharacter(0,false)}
function animateDance(){if(window.gsap){gsap.killTweensOf(danceCharacter);gsap.fromTo(danceCharacter,{scale:.75,rotation:-8,y:12},{scale:1,rotation:0,y:0,duration:.45,ease:'back.out(1.8)',onComplete:()=>gsap.to(danceCharacter,{rotation:7,y:-8,x:4,duration:.32,yoyo:true,repeat:3,ease:'sine.inOut'})})}else danceCharacter.animate([{transform:'rotate(-7deg) translateY(4px)'},{transform:'rotate(7deg) translateY(-7px)'},{transform:'rotate(-5deg) translateY(1px)'}],{duration:900,iterations:1})}
function selectCharacter(index,shouldScroll=true){selectedIndex=(index+characters.length)%characters.length;const c=characters[selectedIndex];lineArtImage.src=lineUrl(c);selectedName.textContent=c.name;spriteStyle(danceCharacter,c);[...carousel.children].forEach((el,i)=>el.classList.toggle('selected',i===selectedIndex));pauseCarousel();if(shouldScroll){carousel.children[selectedIndex]?.scrollIntoView({behavior:'auto',inline:'center',block:'nearest'});carouselPosition=carousel.scrollLeft}clearTimeout(carousel._resumeTimer);carousel._resumeTimer=setTimeout(resumeCarousel,1800);animateDance()}
function setupPalette(){const palette=document.querySelector('#palette');paletteColors.forEach((color,i)=>{const b=document.createElement('button');b.className='color-dot'+(i===0?' active':'');b.style.background=color;b.type='button';b.setAttribute('aria-label',`Use color ${color}`);b.addEventListener('click',()=>{currentColor=color;erasing=false;document.querySelector('#eraserBtn').classList.remove('active');[...palette.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')});palette.appendChild(b)})}
function clearPaint(){paintCtx.clearRect(0,0,paintCanvas.width,paintCanvas.height)}
function resizeCanvases(preserve=true){const r=canvasShell.getBoundingClientRect(),old=preserve?paintCanvas.toDataURL('image/png'):null,dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));paintCanvas.width=lineCanvas.width=w;paintCanvas.height=lineCanvas.height=h;paintCanvas.style.width=lineCanvas.style.width=r.width+'px';paintCanvas.style.height=lineCanvas.style.height=r.height+'px';drawLineArt();if(old){const im=new Image();im.onload=()=>paintCtx.drawImage(im,0,0,w,h);im.src=old}}
function drawLineArt(){const w=lineCanvas.width,h=lineCanvas.height;lineCtx.clearRect(0,0,w,h);lineCtx.fillStyle='#fff';lineCtx.fillRect(0,0,w,h);if(!lineArtImage.complete||!lineArtImage.naturalWidth){lineArtImage.onload=drawLineArt;return}const scale=Math.min(w/lineArtImage.naturalWidth,h/lineArtImage.naturalHeight)*.82,dw=lineArtImage.naturalWidth*scale,dh=lineArtImage.naturalHeight*scale,dx=(w-dw)/2,dy=(h-dh)/2;lineCtx.drawImage(lineArtImage,dx,dy,dw,dh)}
function getPoint(e){const r=paintCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(paintCanvas.width/r.width),y:(e.clientY-r.top)*(paintCanvas.height/r.height)}}
function beginDraw(e){drawing=true;paintCanvas.setPointerCapture?.(e.pointerId);lastPt=getPoint(e)}
function continueDraw(e){if(!drawing)return;const p=getPoint(e);paintCtx.save();paintCtx.lineCap='round';paintCtx.lineJoin='round';paintCtx.lineWidth=brushSize*(paintCanvas.width/Math.max(1,paintCanvas.getBoundingClientRect().width));paintCtx.globalCompositeOperation=erasing?'destination-out':'source-over';paintCtx.strokeStyle=currentColor;paintCtx.beginPath();paintCtx.moveTo(lastPt.x,lastPt.y);paintCtx.lineTo(p.x,p.y);paintCtx.stroke();paintCtx.restore();lastPt=p}
function endDraw(){drawing=false;lastPt=null}
function showColorScreen(increment=false){if(increment)pageVariant++;pickerScreen.classList.add('hidden');colorScreen.classList.remove('hidden');pageTitle.textContent=characters[selectedIndex].name;pageNumber.textContent=`Page ${pageVariant}`;requestAnimationFrame(()=>resizeCanvases(false))}
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;if(window.gsap){gsap.killTweensOf(t);gsap.fromTo(t,{opacity:0,y:20},{opacity:1,y:0,duration:.2,onComplete:()=>gsap.to(t,{opacity:0,y:16,duration:.25,delay:1.25})})}else{t.style.opacity=1;setTimeout(()=>t.style.opacity=0,1500)}}
const DB_NAME='dandy-coloring-studio',STORE='pages';
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function savePage(){const merged=document.createElement('canvas');merged.width=lineCanvas.width;merged.height=lineCanvas.height;const c=merged.getContext('2d');c.drawImage(lineCanvas,0,0);c.drawImage(paintCanvas,0,0);const png=merged.toDataURL('image/png'),id=activeSaveId||`${characters[selectedIndex].name}-${Date.now()}`;activeSaveId=id;const db=await openDB(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,character:characters[selectedIndex].name,characterIndex:selectedIndex,pageVariant,png,paint:paintCanvas.toDataURL('image/png'),savedAt:new Date().toISOString()});showToast('Saved on this device')}
function printPage(){const merged=document.createElement('canvas');merged.width=lineCanvas.width;merged.height=lineCanvas.height;const c=merged.getContext('2d');c.drawImage(lineCanvas,0,0);c.drawImage(paintCanvas,0,0);const w=window.open('','_blank');if(!w){showToast('Please allow pop-ups to print.');return}w.document.write(`<html><head><title>${characters[selectedIndex].name} coloring page</title><style>html,body{margin:0}img{width:100vw;height:100vh;object-fit:contain}</style></head><body><img src="${merged.toDataURL('image/png')}" onload="window.print();setTimeout(()=>window.close(),500)"></body></html>`);w.document.close()}
const musicTracks=[`${ASSET_ROOT}/music/carefree.mp3`,`${ASSET_ROOT}/music/hyperfun.mp3`],bgAudio=new Audio();bgAudio.preload='auto';bgAudio.volume=.28;let musicTrackIndex=0,musicEnabled=false;const musicToggle=document.querySelector('#musicToggle'),musicVolume=document.querySelector('#musicVolume');function loadMusicTrack(index){musicTrackIndex=((index%musicTracks.length)+musicTracks.length)%musicTracks.length;bgAudio.src=musicTracks[musicTrackIndex];bgAudio.load()}function updateMusicButton(){musicToggle.classList.toggle('active',musicEnabled);musicToggle.setAttribute('aria-pressed',String(musicEnabled));musicToggle.textContent=musicEnabled?'♫ Music on':'♪ Music'}async function startMusic(){musicEnabled=true;updateMusicButton();try{if(!bgAudio.src)loadMusicTrack(musicTrackIndex);await bgAudio.play()}catch(e){musicEnabled=false;updateMusicButton()}}function stopMusic(){musicEnabled=false;bgAudio.pause();updateMusicButton()}musicToggle.addEventListener('click',()=>musicEnabled?stopMusic():startMusic());musicVolume.addEventListener('input',e=>bgAudio.volume=Number(e.target.value));bgAudio.addEventListener('ended',()=>{if(!musicEnabled)return;loadMusicTrack(musicTrackIndex+1);bgAudio.play().catch(()=>{musicEnabled=false;updateMusicButton()})});loadMusicTrack(0);updateMusicButton();
document.querySelector('#prevBtn').onclick=()=>selectCharacter(selectedIndex-1);document.querySelector('#nextBtn').onclick=()=>selectCharacter(selectedIndex+1);document.querySelector('#colorBtn').onclick=()=>{pauseCarousel();pageVariant=1;activeSaveId=null;clearPaint();showColorScreen(false)};document.querySelector('#backBtn').onclick=()=>{colorScreen.classList.add('hidden');pickerScreen.classList.remove('hidden');animateDance();resumeCarousel()};document.querySelector('#newPageBtn').onclick=()=>{clearPaint();activeSaveId=null;showColorScreen(true)};document.querySelector('#saveBtn').onclick=savePage;document.querySelector('#printBtn').onclick=printPage;document.querySelector('#clearBtn').onclick=()=>{clearPaint();showToast('Page cleared')};document.querySelector('#eraserBtn').onclick=e=>{erasing=!erasing;e.currentTarget.classList.toggle('active',erasing)};document.querySelector('#brushSize').oninput=e=>brushSize=+e.target.value;paintCanvas.addEventListener('pointerdown',beginDraw);paintCanvas.addEventListener('pointermove',continueDraw);paintCanvas.addEventListener('pointerup',endDraw);paintCanvas.addEventListener('pointercancel',endDraw);paintCanvas.addEventListener('pointerleave',e=>{if(e.buttons===0)endDraw()});window.addEventListener('resize',()=>{if(colorScreen.classList.contains('hidden'))return;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>resizeCanvases(true),150)});carousel.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();selectCharacter(selectedIndex-1)}if(e.key==='ArrowRight'){e.preventDefault();selectCharacter(selectedIndex+1)}});setupPalette();buildCarousel();setupCarouselMotion();